version: '3.1'

services:
  author:
    build:
      context: ./magnolia
      args:
        CONF_CONTEXT_FILE: config/context-author.xml
        CONF_PROPERTIES_FILE: config/magnolia-author.properties
    container_name: magnolia-author
    networks:
      - magnolia
    ports:
      - 3000:8080
    volumes:
      - /D/Var Data/www/html/magnolia/magnolia-author:/data/magnolia
  public1:
    build:
      context: ./magnolia
      args:
        CONF_CONTEXT_FILE: config/context-public.xml
        CONF_PROPERTIES_FILE: config/magnolia-public.properties
    container_name: magnolia-public1
    networks:
      - magnolia
    ports:
      - 3001:8080
    volumes:
      - /D/Var Data/www/html/magnolia/magnolia-public1:/data/magnolia

networks:
  magnolia: